# Generated by Django 4.2 on 2025-11-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analysis.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('relevance_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('accuracy_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('completeness_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('empathy_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('response_time_avg', models.FloatField(default=0.0, help_text='Average seconds (mock)')),
                ('resolution', models.BooleanField(default=False, help_text='Was issue resolved?')),
                ('escalation_needed', models.BooleanField(default=False, help_text='Needs human escalation?')),
                ('fallback_count', models.IntegerField(default=0, help_text="Times AI said 'I don't know'")),
                ('overall_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analysis.conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
